---
name: Tests

'on':
  - pull_request
  - push

jobs:

  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Install package and dependencies
        run: |
          sudo apt-get install golang-1.18
      - name: Run Tests
        run: go test -v ./...
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup E2E testing environment
        run: docker compose -f deployments/compose.yaml up -d --build
      - name: Wait for Keycloak import to complete
        run: deployments/wait_for_keycloak_import.sh deployments/compose.yaml
      - name: Install test environment
        run: npm --prefix test ci
      - name: E2E tests
        run: npm --prefix test test
